version: "3"
services:
  datastone:
    image: teste/datastone
    build:
      context: .
    volumes:
      - .:/var/www/
    ports:
      - "8000:8000"
    links:
      - "database:database"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database/postgres
      # - DEPLOY=true
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/advocacydb
volumes:
  database:
